const themes = [
    {
        name: "dark",
        primaryColor: "#0a0a0a",
        secondaryColor: "#E0E0E0",
        placeholderText: "#555555",
        lowerOpacityText: "#64B5F6",
        containerBg: "#1E1E1E",
        buttonBg: "#222222",
        errorButtonBg: "#D32F2F",
        buttonText: "#FFFFFF",
        errorColor: "#E53935",
        textOnError: "#FFFFFF",
        titleColor: "#006ccc"
    },
    {
        name: "light",
        primaryColor: "#FAFAFA",
        secondaryColor: "#212121",
        placeholderText: "rgba(33, 33, 33, 0.5)",
        lowerOpacityText: "#1E88E5",
        containerBg: "#e5e5e5",
        buttonBg: "#1E88E5",
        errorButtonBg: "#D32F2F",
        buttonText: "#FFFFFF",
        errorColor: "#E53935",
        textOnError: "#FFFFFF",
        titleColor: "#000000"
    },
    {
        name: "hacker",
        primaryColor: "#0F0F0F",
        secondaryColor: "#00FF00",
        placeholderText: "rgba(0, 255, 0, 0.34)",
        lowerOpacityText: "#00FF00",
        containerBg: "#0a0a0a",
        buttonBg: "#e85c8c",
        buttonText: "#000000",
        errorColor: "#FF1744",
        textOnError: "#121212",
        titleColor: "#00FF00"
    },
    {
        name: "cloud",
        primaryColor: "#90A4AE",
        secondaryColor: "#ECEFF1",
        placeholderText: "rgb(199, 199, 199)",
        lowerOpacityText: "#B0BEC5",
        containerBg: "#546E7A",
        buttonBg: "#5a666c",
        buttonText: "#F1F1F1",
        errorColor: "#EF5350",
        textOnError: "#FFFFFF",
        titleColor: "#ECEFF1"
    },
    {
        name: "steel",
        primaryColor: "#546E7A",
        secondaryColor: "#CFD8DC",
        placeholderText: "rgb(155, 155, 155)",
        lowerOpacityText: "#90A4AE",
        containerBg: "#263238",
        buttonBg: "#78909C",
        buttonText: "#ECEFF1",
        errorColor: "#FF5252",
        textOnError: "#FFFFFF",
        titleColor: "#ECEFF1"
    },
    {
        name: "sunset",
        primaryColor: "#FF7043",
        secondaryColor: "#FFE0B2",
        placeholderText: "rgba(255, 224, 178, 0.5)",
        lowerOpacityText: "#FFAB91",
        containerBg: "#8C3B1C",
        buttonBg: "#D84315",
        buttonText: "#FFEDE0",
        errorColor: "#D32F2F",
        textOnError: "#FFF3E0",
        titleColor: "#FFF3E0"
    },
    {
        name: "midnight",
        primaryColor: "#3F51B5",
        secondaryColor: "#C5CAE9",
        placeholderText: "#9FA8DA",
        lowerOpacityText: "#7986CB",
        containerBg: "#121858",
        buttonBg: "#303F9F",
        buttonText: "#E3E6F6",
        errorColor: "#EF5350",
        textOnError: "#FFFFFF",
        titleColor: "#E8EAF6"
    },
    {
        name: "sand",
        primaryColor: "#A1887F",
        secondaryColor: "#FFF8E1",
        placeholderText: "rgba(65, 64, 57, 0.5)",
        lowerOpacityText: "#D7CCC8",
        containerBg: "#5D4037",
        buttonBg: "#A1887F",
        buttonText: "#FFF3E0",
        errorColor: "#C62828",
        textOnError: "#FFF8E1",
        titleColor: "#FFFDE7"
    },
    {
        name: "blush",
        primaryColor: "#d1859f",
        secondaryColor: "#f2e7ea",
        placeholderText: "rgba(242, 231, 234, 0.5)",
        lowerOpacityText: "#F8BBD0",
        containerBg: "#d14c75",
        buttonBg: "#EC407A",
        buttonText: "#FFF4F7",
        errorColor: "#a70000",
        textOnError: "#FFF0F5",
        titleColor: "#FFFFFF"
    },
    {
        name: "cyberpunk",
        primaryColor: "#FFD600",
        secondaryColor: "#212121",
        placeholderText: "rgba(33, 33, 33, 0.5)",
        lowerOpacityText: "#00E5FF",
        containerBg: "#fff066",
        buttonBg: "#00C4FF",
        buttonText: "#212121",
        errorColor: "#FF1744",
        textOnError: "#1B1B1B",
        titleColor: "#0f0f0f"
    },
    {
        name: "forest",
        primaryColor: "#6ac46d",
        secondaryColor: "#E8F5E9",
        placeholderText: "rgba(0, 0, 0, 0.4)",
        lowerOpacityText: "#A5D6A7",
        containerBg: "#256D27",
        buttonBg: "#43A047",
        buttonText: "#F1F8E9",
        errorColor: "#C62828",
        textOnError: "#FFFFFF",
        titleColor: "#FFFFFF"
    },
    {
        name: "pastel",
        primaryColor: "#BA68C8",
        secondaryColor: "#F3E5F5",
        placeholderText: "rgb(185, 185, 185)",
        lowerOpacityText: "#CE93D8",
        containerBg: "#8E24AA",
        buttonBg: "#68b1c8",
        buttonText: "#FDEBFF",
        errorColor: "#D81B60",
        textOnError: "#FFFFFF",
        titleColor: "#FFFFFF"
    },
    {
        name: "ocean",
        primaryColor: "#00ACC1",
        secondaryColor: "#E0F7FA",
        placeholderText: "rgb(194, 194, 194)",
        lowerOpacityText: "#4DD0E1",
        containerBg: "#005662",
        buttonBg: "#00bf71",
        buttonText: "#E0F2F1",
        errorColor: "#E53935",
        textOnError: "#FFFFFF",
        titleColor: "#E0F7FA"
    },
    {
        name: "mystic",
        primaryColor: "#7E57C2",
        secondaryColor: "#EDE7F6",
        placeholderText: "rgb(194, 194, 194)",
        lowerOpacityText: "#B39DDB",
        containerBg: "#4527A0",
        buttonBg: "#f1f752",
        buttonText: "#f75252",
        errorColor: "#C62828",
        textOnError: "#FFFFFF",
        titleColor: "#FFFFFF"
    },

];

export default themes;
